# Generated by Django 5.1.9 on 2025-05-18 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(max_length=50)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('vote_count', models.IntegerField(blank=True, null=True)),
                ('is_voted', models.BooleanField(default=False)),
                ('prompt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.prompt')),
            ],
        ),
        migrations.CreateModel(
            name='BackupAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.prompt')),
            ],
            options={
                'verbose_name': 'Backup Answer',
                'verbose_name_plural': 'Backup Answers',
                'db_table': 'backup_answers',
            },
        ),
    ]
