# Generated by Django 5.1.9 on 2025-05-16 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='name',
        ),
    ]
