# Generated by Django 5.1.9 on 2025-05-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_player_answer_player_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='vote_telegram_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
