# Generated by Django 5.1.9 on 2025-05-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_player_vote_telegram_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='vote_telegram_id',
        ),
        migrations.AddField(
            model_name='player',
            name='vote_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
