# Generated by Django 5.1.9 on 2025-05-17 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_started_alter_game_code_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='game',
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
