# Generated by Django 5.1.9 on 2025-05-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_player_vote_telegram_id_player_vote_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='prompt',
            new_name='prompt_id',
        ),
        migrations.AddField(
            model_name='player',
            name='is_voted',
            field=models.BooleanField(default=False),
        ),
    ]
